"""Native Manim SRT parsing, transcription and deterministic concatenation."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

_TIMESTAMP = re.compile(r"(?P<h>\d{2}):(?P<m>\d{2}):(?P<s>\d{2})[,.](?P<ms>\d{3})")


@dataclass(frozen=True)
class SubtitleCue:
    """One subtitle interval expressed in milliseconds."""

    start_ms: int
    end_ms: int
    text: str


class SubtitleService:
    """Transform the subcaptions generated by Manim Voiceover."""

    @staticmethod
    def parse(content: str) -> tuple[SubtitleCue, ...]:
        """Parse standard SRT content without accepting malformed intervals."""
        cues: list[SubtitleCue] = []
        normalized = content.replace("\r\n", "\n").strip()
        if not normalized:
            return ()
        for block in re.split(r"\n\s*\n", normalized):
            lines = block.splitlines()
            if lines and lines[0].strip().isdigit():
                lines = lines[1:]
            if len(lines) < 2 or "-->" not in lines[0]:
                raise ValueError("Arquivo SRT inválido: intervalo ausente.")
            start_text, end_text = (part.strip() for part in lines[0].split("-->", 1))
            start_ms = _parse_timestamp(start_text)
            end_ms = _parse_timestamp(end_text)
            text = "\n".join(lines[1:]).strip()
            if end_ms < start_ms or not text:
                raise ValueError("Arquivo SRT inválido: legenda vazia ou intervalo invertido.")
            cues.append(SubtitleCue(start_ms, end_ms, text))
        return tuple(cues)

    @classmethod
    def transcript(cls, content: str) -> str:
        """Return plain narration text, preserving cue and line order."""
        cues = cls.parse(content)
        if not cues:
            return ""
        return "\n".join(cue.text.replace("\n", " ") for cue in cues) + "\n"

    @classmethod
    def combine(cls, first: str, second: str, *, offset_seconds: float) -> str:
        """Append ``second`` after ``first`` using the first video's duration."""
        offset_ms = max(0, round(offset_seconds * 1000))
        cues = list(cls.parse(first))
        cues.extend(
            SubtitleCue(cue.start_ms + offset_ms, cue.end_ms + offset_ms, cue.text)
            for cue in cls.parse(second)
        )
        return cls.render(tuple(cues))

    @staticmethod
    def render(cues: tuple[SubtitleCue, ...]) -> str:
        """Render cues as canonical UTF-8 SRT content."""
        blocks = [
            (
                f"{index}\n{_format_timestamp(cue.start_ms)} --> "
                f"{_format_timestamp(cue.end_ms)}\n{cue.text}"
            )
            for index, cue in enumerate(cues, start=1)
        ]
        return "\n\n".join(blocks) + ("\n" if blocks else "")

    @classmethod
    def transcript_file(cls, subtitle_path: Path) -> str:
        """Read a native SRT file and return its plain text transcript."""
        return cls.transcript(subtitle_path.read_text(encoding="utf-8-sig"))


def _parse_timestamp(value: str) -> int:
    match = _TIMESTAMP.fullmatch(value)
    if match is None:
        raise ValueError(f"Timestamp SRT inválido: {value!r}.")
    return (
        int(match["h"]) * 3_600_000
        + int(match["m"]) * 60_000
        + int(match["s"]) * 1000
        + int(match["ms"])
    )


def _format_timestamp(milliseconds: int) -> str:
    hours, remainder = divmod(milliseconds, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    seconds, millis = divmod(remainder, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"
